services:
  - name: user-service
    desc: 用户服务
    jar: /opt/user.jar
    status: running
    port: 8081

  - name: order-service
    desc: 订单服务
    jar: /opt/order.jar
    status: stopped
    port: 8082
